name: Java CI with Maven

on:
  push:
    # Start CI process only when code is pushed to master and dev
    branches: [ master, dev ]

jobs:
  #  build-on-windows:
  #    run-on: windows-latest
  #  Copy the same process as in Linux
  #  build-on-macos:
  #    run-on: macos-latest
  #  Copy the same process as in Linux
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      # Set up Java
      - uses: actions/checkout@v2
      - name: Step 1 - Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build with maven without test
      - name: Step 2 - Build and Unit test with Maven
        run: mvn package -Dmaven.test.skip=true

      # Caching Maven dependency for CI performance
      - name: Step 3 - Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-



